version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: MAXDeliveryNG/helm-charts
            - GITHUB_PAGES_BRANCH: gh-pages
            - HELM_VERSION: 3.4.2
      # - run:
      #     name: Verify
      #     command: |
      #       alias helm=/tmp/helm/bin/linux-amd64/helm
      #       if [ "$CIRCLE_BRANCH" = "master" ]; then
      #         helm repo add MAXDeliveryNG https://maxdeliveryng.github.io/helm-charts
      #         helm repo update
      #         helm repo list
      #         helm inspect MAXDeliveryNG/welfare-service
      #       fi
